@ShopeeFlow_HostAddress = http://localhost:5227
@ApiToken = PASTE_TOKEN_FROM_APPSETTINGS_ApiSecurity_AccessToken

### Search product offers (requires X-Api-Key)
GET {{ShopeeFlow_HostAddress}}/ProductOffer?sortType=5&isAmsOffer=true&limit=1
Accept: application/json
X-Api-Key: {{ApiToken}}
